services:
  mongodb:
    image: mongo:latest
    container_name: firefly_parser_bot_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db
    restart: always
    networks:
      - firefly-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firefly-sms-parser
    depends_on:
      - mongodb
    volumes:
      - ./config.ini:/app/config.ini
      - ./workdir:/app/workdir
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    restart: always
    networks:
      - firefly-network

networks:
  firefly-network:
    driver: bridge

