version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - firefly-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firefly-sms-parser
    depends_on:
      - mongodb
    volumes:
      - ./config.ini:/app/config.ini
      - ./workdir:/app/workdir
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    restart: always
    networks:
      - firefly-network

networks:
  firefly-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
